#!/bin/bash
DATE="`date '+%Y%m%d%H%M'`"
FILE=/root/cycler_data/config/parameter/AppControl_Config
cd /root/cycler_data

tar cvfz `cat $FILE | awk '{if(NR==1) print $3}'`_config_backup_$DATE.tar.gz config
echo "config_backup end."
