#ifndef __APPCONTROL_DEF_H__
#define __APPCONTROL_DEF_H__

// AppControl Signal
#define APP_SIG_APP_CONTROL_PROCESS			0
#define APP_SIG_MAIN_CLIENT_PROCESS			1
#define APP_SIG_DATA_SAVE_PROCESS			2
#define APP_SIG_MAINTENANCE_UI_PROCESS		3
#define APP_SIG_CALI_METER_PROCESS			4
#define APP_SIG_CALI_CONTROL_PROCESS		5
#define APP_SIG_MODULE_CONTROL_PROCESS		6
#define APP_SIG_QUIT						7
#define APP_SIG_MAIN_CLIENT_PROCESS_CHECK	8
#define APP_SIG_MONITOR_CLIENT_PROCESS_CHECK	9
#define APP_SIG_CALI_METER_PROCESS_CHECK	10
#define APP_SIG_TIMER_1SEC					11
#define APP_SIG_ANALOG_METER_PROCESS		12
#define APP_SIG_ANALOG_METER_PROCESS_CHECK	13
#define APP_SIG_FADM_PROCESS				14
#define APP_SIG_FADM_PROCESS_CHECK			15
#define APP_SIG_FND_METER_PROCESS			16
#define APP_SIG_FND_METER_PROCESS_CHECK		17
#define APP_SIG_CALI_METER2_PROCESS			18
#define APP_SIG_CALI_METER2_PROCESS_CHECK	19
#define APP_SIG_EXT_CLIENT_PROCESS			20
#define APP_SIG_EXT_CLIENT_PROCESS_CHECK	21
#define APP_SIG_ANALOG_METER2_PROCESS		22
#define APP_SIG_ANALOG_METER2_PROCESS_CHECK	23
#define APP_SIG_AUTO_UPDATE_PROCESS			24	//20190626 oys
#define APP_SIG_AUTO_UPDATE_PROCESS_CHECK	25	//20190626 oys
#define APP_SIG_DAQ_CLIENT_PROCESS			26	//220310 hun
#define APP_SIG_DAQ_CLIENT_PROCESS_CHECK	27	//220310 hun
#define APP_SIG_COOLING_CONTROL_PROCESS			28	//220302 jws add
#define APP_SIG_COOLING_CONTROL_PROCESS_CHECK	29	//220302 jws add

//Load_Process
#define		LOAD_MAINCLIENT					0
#define		LOAD_DATASAVE					1
#define		LOAD_CALIMETER					2
#define		LOAD_ANALOGMETER				3
#define		LOAD_FADM						4
#define		LOAD_FNDMETER					5
#define		LOAD_MCONTROL					6
#define		LOAD_CALIMETER2					7
#define		LOAD_EXTCLIENT					8
#define		LOAD_ANALOGMETER2				9
#define		LOAD_AUTOUPDATE					10	//20190626 oys
#define		LOAD_DAQ_CLIENT					11	//20220310 hun
#define		LOAD_COOLINGCONTROL				12	//220302 jws add
#endif
