#ifndef __DATASAVE_DEF_H__
#define __DATASAVE_DEF_H__

//DataSave define
#define MAX_RESULT_FILE_INDEX			7

// DataSave Signal
#define DATASAVE_SIG_SAVED_FILE_DELETE	0
#define DATASAVE_SIG_SAVED_FILE_DELETE_IDX	1
#define DATASAVE_SIG_RCVED_CONTINUE_CMD	2
#define DATASAVE_SIG_RCVED_CONTINUE_CMD_IDX	3

#endif
