#ifndef __MESSAGE_DEF_H__
#define __MESSAGE_DEF_H__

/* start message define */
#define MAX_MSG_RING				64 //20160229 Modified
#define MAX_MSG						128
#define MAX_SAVE_MSG				256
#define MAX_PULSE_DATA				350
#define MAX_PULSE_DATA_IEC			152
#define MAX_PULSE_MSG				384
#define	MAX_10MS_MSG				102

//message direction
#define APP_TO_MAIN					0
#define APP_TO_MODULE				1
#define APP_TO_DATASAVE				2
#define APP_TO_METER				3
#define MAIN_TO_APP					4
#define MAIN_TO_MODULE				5
#define MAIN_TO_DATASAVE			6
#define MAIN_TO_METER				7
#define MODULE_TO_APP				8
#define MODULE_TO_MAIN				9
#define MODULE_TO_DATASAVE			10
#define MODULE_TO_METER				11
#define DATASAVE_TO_APP				12
#define DATASAVE_TO_MAIN			13
#define DATASAVE_TO_MODULE			14
#define DATASAVE_TO_METER			15
#define METER_TO_APP				16
#define METER_TO_MAIN				17
#define METER_TO_MODULE				18
#define METER_TO_DATASAVE			19
#define APP_TO_METER2				20
#define MODULE_TO_METER2			21
#define PSKILL_TO_MODULE			22

#define APP_TO_CALIMETER2			23 //20160229
#define MAIN_TO_CALIMETER2			24 //20160229
#define MODULE_TO_CALIMETER2		25 //20160229
#define DATASAVE_TO_CALIMETER2		26 //20160229
#define CALIMETER2_TO_APP			27 //20160229
#define CALIMETER2_TO_MAIN			28 //20160229
#define CALIMETER2_TO_MODULE		29 //20160229
#define CALIMETER2_TO_DATASAVE		30 //20160229

#define APP_TO_EXT					31 //20160229
#define MAIN_TO_EXT					32 //20160229
#define MODULE_TO_EXT				33 //20160229
#define DATASAVE_TO_EXT				34 //20160229
#define METER_TO_EXT				35 //20160229
#define EXT_TO_APP					36 //20160229
#define EXT_TO_MAIN					37 //20160229
#define EXT_TO_MODULE				38 //20160229
#define EXT_TO_DATASAVE				39 //20160229
#define EXT_TO_METER				40 //20160229

#define APP_TO_ANALOGMETER2			41

#define MODULE_TO_APP_VALUE 		45 //20190527
#define MODULE_TO_DATASAVE_PATTERN	46 //20191120
#define MAIN_TO_METER2				47 //200102 add
#define METER2_TO_MAIN				48 //200102 add

#define COOLING_TO_APP				49 //220302 jws add
#define COOLING_TO_MODULE			50 //220302 jws add

//AppControl to Module 1
#define MSG_APP_MODULE_EXIT			1
#define MSG_APP_MODULE_CH_CALI		2
#define MSG_APP_MODULE_SAVE_START	3
#define MSG_APP_MODULE_SAVE_STOP	4
#define MSG_APP_MODULE_AUX_CALI_LOW		5
#define MSG_APP_MODULE_AUX_CALI_HIGH	6
#define MSG_APP_MODULE_AUX_CALI_UPDATE	7
#define MSG_APP_MODULE_D_CALI_UPDATE	8	//20180813 lyhw add

//AppControl to DataSave 2

//AppControl to CaliMeter 3
#define MSG_APP_METER_INITIALIZE	1
#define MSG_APP_METER_REQUEST		2

//MainClient to AppControl 4
#define MSG_MAIN_APP_PROCESS_KILL			1
#define MSG_MAIN_APP_WRITE_CHATTRIBUTE		2
#define MSG_MAIN_APP_WRITE_AUX_SET_DATA		3
#define MSG_MAIN_APP_WRITE_CHCOMPDATA		4
#define MSG_MAIN_APP_WRITE_LIMIT_USER_VI	5	//20171008 sch add
#define MSG_MAIN_APP_PARAMETER_UPDATE		6	//190801 lyhw
#define MSG_MAIN_APP_WRITE_HWFAULT_CONFIG	7	//210204 lyhw
#define MSG_MAIN_APP_WRITE_CHAMBER_CH_NO	8	//210415 hun needCheck
#define MSG_MAIN_APP_WRITE_SW_FAULT_CONFIG	9	//210415 hun needCheck
#define MSG_MAIN_APP_WRITE_LGES_FAULT_CONFIG 10	//211025 hun
#define MSG_MAIN_APP_WRITE_SDI_CC_CV_HUMP_CONFIG 11	//211025 hun
#define MSG_MAIN_APP_WRITE_SDI_PAUSE_SAVE_CONFIG 12	//211025 hun
#define MSG_MAIN_APP_WRITE_DYSON_MAINTENANCE_CONFIG 13	//220118 jsh

//ExtClient to AppControl 4
#define MSG_EXT_APP_PROCESS_KILL	1
#define MSG_EXT_APP_WRITE_CHATTRIBUTE	2
#define MSG_EXT_APP_WRITE_AUX_SET_DATA 3
#define MSG_EXT_APP_WRITE_CHCOMPDATA	4

//MainClient to Module 5
#define MSG_MAIN_MODULE_CH_CALI		1
#define MSG_MAIN_MODULE_CALI_RELAY	2
#define MSG_MAIN_MODULE_SAVE_MSG_FLAG	3
#define MSG_MAIN_MODULE_SHUTDOWN_FLAG	4 //181108 GUI TO SBC SHUTDOWN 
#define MSG_MAIN_MODULE_CHAMBER_FAULT	5 //220214_hun

//MainClient to DataSave 6
#define MSG_MAIN_DATASAVE_SAVED_FILE_DELETE	1
#define MSG_MAIN_DATASAVE_RCVED_CONTINUE_CMD	2
#define MSG_MAIN_DATASAVE_READ_USER_SOC_TRACKING			3
#define MSG_MAIN_DATASAVE_READ_USER_CHARGING_COUNT_FILE	4
#define MSG_MAIN_DATASAVE_READ_USER_CHARGING_RPT_SOC		5

//MainClient to CaliMeter 7
#define MSG_MAIN_METER_INITIALIZE	1
#define MSG_MAIN_METER_WRITE_SET	2

//Module to AppControl 8
#define MSG_MODULE_APP_POWER_SWITCH		1
#define MSG_MODULE_APP_EMG				2
#define MSG_MODULE_APP_PROCESS_KILL		3
#define MSG_MODULE_APP_AUX_CALI			4
#define MSG_MODULE_APP_OVP				5
#define MSG_MODULE_APP_CCC				6
#define MSG_MODULE_APP_OTP				7
#define MSG_MODULE_APP_D_CALI_UPDATE	8	//180813 add
#define MSG_MODULE_APP_CH_EMG			10	//220322_hun

//Module to MainClient 9
#define MSG_MODULE_MAIN_EMG_STATUS			1
#define MSG_MODULE_MAIN_JIG_STATUS			2
#define MSG_MODULE_MAIN_STEP_COND_UPDATE	3
#define MSG_MODULE_MAIN_GOTO_COUNT_UPDATE	4

//Module to DataSave 10
#define MSG_MODULE_DATASAVE_CALI_NORMAL_RESULT_SAVE	1
#define MSG_MODULE_DATASAVE_CALI_CHECK_RESULT_SAVE	2
#define MSG_MODULE_DATASAVE_READ_USER_PATTERN		3
#define MSG_MODULE_DATASAVE_READ_USER_MAP			4
#define MSG_MODULE_DATASAVE_READ_USER_SOC_TRACKING			5

//Module to CaliMeter 11
#define MSG_MODULE_METER_REQUEST	1

//DataSave to MainClient 13
#define MSG_DATASAVE_MAIN_CALI_NORMAL_RESULT_SEND	1
#define MSG_DATASAVE_MAIN_CALI_CHECK_RESULT_SEND	2
#define MSG_DATASAVE_MAIN_READ_FAIL_USER_PATTERN	3

//DataSave to Module 14
#define MSG_DATASAVE_MODULE_CH_RUN	1
#define MSG_DATASAVE_MODULE_CALI_NORMAL_RESULT_SAVED	2
#define MSG_DATASAVE_MODULE_CALI_CHECK_RESULT_SAVED	3
#define MSG_DATASAVE_MODULE_CH_CONTINUE	4
#define MSG_DATASAVE_MODULE_READ_SUCESS_USER_PATTERN		5
#define MSG_DATASAVE_MODULE_READ_FAIL_USER_PATTERN		6
#define MSG_DATASAVE_MODULE_READ_SUCESS_USER_MAP		7
#define MSG_DATASAVE_MODULE_READ_FAIL_USER_MAP		8
#define MSG_DATASAVE_MODULE_READ_SUCESS_USER_SOC	9
#define MSG_DATASAVE_MODULE_READ_FAIL_USER_SOC		10

//CaliMeter to MainClient 17
#define MSG_METER_MAIN_INITIALIZE_REPLY	1

//CaliMeter to Module 18
#define MSG_METER_MODULE_REQUEST_REPLY	1

//AppControl to AnalogMeter or FADM 20
#define MSG_APP_METER2_INITIALIZE			1
#define MSG_APP_METER2_MEASURE				2
#define MSG_APP_METER2_REQUEST				3
#define MSG_APP_METER2_COMM_CHECK			4
#define MSG_APP_METER2_WR_BASE_ADDR			5
#define MSG_APP_METER2_CALI_H				6
#define MSG_APP_METER2_CALI_L				7
#define MSG_APP_METER2_CALI_WRITE			8
#define MSG_APP_METER2_CALI_UPDATE			9
#define MSG_APP_METER2_CALI_MULTI			10
#define MSG_APP_METER2_CALI_MULTI_WRITE		11
#define MSG_APP_METER2_CALI_MULTI_UPDATE	12
#define MSG_APP_METER2_CALI_AUTO			13

//MainClient to AnalogMeter
#define MSG_MAIN_METER2_WRITE_TEMP_CALI_DATA	1  //200102 add
#define MSG_MAIN_METER2_TEMP_CALI_START			2  //200102 add
#define MSG_MAIN_METER2_TEMP_CALI_BACKUP_READ	3  //200102 add
#define MSG_MAIN_METER2_TEMP_CALI_CLEAR			4  //200102 add

//AnalogMeter to MainClient
#define MSG_METER2_MAIN_TEMP_CALI_BACKUP_READ_REPLY	1  //2000102 add

//Module to FADM 2
#define MSG_MODULE_METER2_MEASURE 	1

//Module to EXT
#define MSG_MODULE_EXT_EMG_STATUS 	1

//PSKILL to MODULE 22
#define MSG_PSKILL_MODULE_EXIT		1

//Ext to DataSave 39
#define MSG_EXT_DATASAVE_SAVED_FILE_DELETE  1
#define MSG_EXT_DATASAVE_RCVED_CONTINUE_CMD 2

//Module to DataSave Pattern 46
#define MSG_READ_USER_PATTERN_1		1
#define MSG_READ_USER_PATTERN_2		2

//Module to Meter2
#define MSG_MODULE_METER2_WRITE_TEMP_CALI_DATA 1

//Cooling Control	220302 jws add
#define MSG_COOLING_APP_PROCESS_KILL		1
#define MSG_COOLING_MODULE_SAVE_MSG_FLAG	2

#endif
